language: node_js
node_js:
- v6.11.1
git:
  depth: 1
branches:
  only:
  - master
install: npm install -g gitbook-cli@2.3.0
before_script:
- mv book_github.json book.json
- gitbook fetch 2.0.1
- gitbook install
script:
- rm -rf _book
- gitbook build
after_success:
- bash deploy.sh
env:
  global:
  - GH_REF: github.com/beader/mlnotebook.git
  - secure: EEqu24H9/TTZz0tc/HG1Mt2FLTQ6ODKsSl1w1wR2Pdf3RiKKLUj9q8O6jn4dVC+uCKEBHFa2v3ONFBoLGgm38mqOWpemGLL/aWok7mxGmoEjmflodV5J1eg0zNSX3QJIducPcCQ7Ha4qP/J9SdpboVC95GqXQbQupdZuzpHB8Mp6U5gVhVryRa4vuSBikWyS6lVKTe0iGLnppo87QwHxIKJKlD04p8jahjVCFseapXqOg7Yh3N4bUraGj5YarPNA5dVI8H8KpT4CeMwEphr4aV7+Vv5esU5Gz//wzeU91MHYBi1CusHv2hUP3iHNNTkPrT5aSBlKdc9r2R4kGI2FqqgIBYA837sd0DFE3lLWrpH3rMUwq45zkYcNMfi/EhuSTVH2NRvFvCPH3Hi9RJDf7SKoVa287uIs09pFcuVJLL78iMCudRwcfXtYT7mqr1ly7UDIRPDDYN6icz2Z207lrakBbs9JSP9saDputnTCx+6qmOPaEdCxw5MgHqtaetLQTDzkAO/Zwm7K1UIDJYrkSrmp2t087ElEFApKLVb6CwPq4eMJWO8woqdCFXkB9L8f/QGOHWfRsfJYawj+hLaylCPPKvyBtyQdglk5EvNbNYHvdJTjg0mr0Nd52j1qCvVLq59a3cfkEKV5Nhek9WN4m3b/KwtbXSf9m7pzDUKw4z0=
